### PR TITLE
Allow multiple CC / BCC, Kotlin refactor

### PR DESCRIPTION
**Pull request by NarvalNudiste**
Hey,
 
We started to use maildroid for the mailing part of our company app and I needed to make some changes. 
This should not break anything when migrating from previous versions. 

- Merged the recipient and recipients var into one single list, to be able to add one or more recipients with the same method call
- Did the same for cc, bcc fields
- Reworked the attachment system to allow renaming (filename is optional)
- Unified the log tag (you can of course ignore this if you needed specific tags)

+ Simplified some parts and avoided !! operators .. 

Feel free to ask for changes if anything looks wrong to you. I can also comment unclear parts if needed.

All the best, 
Narval

### CODE REVIEW

**Comment by NarvalNudiste** [comment]
This should solve #46

**Comment by nedimf** [comment]
Amazing work! Thank you for submission.Approved @NarvalNudiste

**Review by nedimf — APPROVED** [review]
LGTM

**Comment by adrixgc** [comment]
Thanks for taking care of the issue!

**Pull request merged**
